Make the husky script even better

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,2 +1,26 @@
-# .husky/pre-commit
-yarn prettier --check --ignore-unknown --plugin=prettier-plugin-solidity $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
+
+# Get a list of staged files that are added, copied, modified, or renamed
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep '\.sol' || true)
+
+# Exit early if no files are staged
+if [ -z "$STAGED_FILES" ]; then
+  echo "No relevant files to format."
+  exit 0
+fi
+
+# Run prettier check
+echo "Running Prettier check..."
+yarn prettier --check --ignore-unknown --plugin=prettier-plugin-solidity $STAGED_FILES
+
+# If Prettier check fails, run Prettier write to fix issues
+if [ $? -ne 0 ]; then
+  echo "Prettier found problems. Fixing...You have to add them to the staging area if you agree with changes."
+  yarn prettier --write --ignore-unknown --plugin=prettier-plugin-solidity $STAGED_FILES
+
+  exit 1
+else
+  echo "Prettier check passed."
+  exit 0
+fi
